//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Sun Dec 10 11:21:14 IST 2023
//
//
// Ports:
// Name                         I/O  size props
// bf16                           O    16
// RDY_bf16                       O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// bf16_fp32                      I    32
//
// Combinational paths from inputs to outputs:
//   bf16_fp32 -> bf16
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFP32toBF16(CLK,
		    RST_N,

		    bf16_fp32,
		    bf16,
		    RDY_bf16);
  input  CLK;
  input  RST_N;

  // value method bf16
  input  [31 : 0] bf16_fp32;
  output [15 : 0] bf16;
  output RDY_bf16;

  // signals for module outputs
  wire [15 : 0] bf16;
  wire RDY_bf16;

  // value method bf16
  assign bf16 = bf16_fp32[31:16] ;
  assign RDY_bf16 = 1'd1 ;
endmodule  // mkFP32toBF16

