//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Sun Dec 10 11:15:49 IST 2023
//
//
// Ports:
// Name                         I/O  size props
// cf8143tofp                     O    32
// RDY_cf8143tofp                 O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// cf8143tofp_cf8143              I     8
// cf8143tofp_bias                I     6
//
// Combinational paths from inputs to outputs:
//   (cf8143tofp_cf8143, cf8143tofp_bias) -> cf8143tofp
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCF8143toFP32(CLK,
		      RST_N,

		      cf8143tofp_cf8143,
		      cf8143tofp_bias,
		      cf8143tofp,
		      RDY_cf8143tofp);
  input  CLK;
  input  RST_N;

  // value method cf8143tofp
  input  [7 : 0] cf8143tofp_cf8143;
  input  [5 : 0] cf8143tofp_bias;
  output [31 : 0] cf8143tofp;
  output RDY_cf8143tofp;

  // signals for module outputs
  wire [31 : 0] cf8143tofp;
  wire RDY_cf8143tofp;

  // remaining internal signals
  wire [7 : 0] x__h65, y__h66, y__h67;

  // value method cf8143tofp
  assign cf8143tofp =
	     { cf8143tofp_cf8143[7],
	       x__h65 + y__h66,
	       cf8143tofp_cf8143[2:0],
	       20'b0 } ;
  assign RDY_cf8143tofp = 1'd1 ;

  // remaining internal signals
  assign x__h65 = 8'b01111111 - y__h67 ;
  assign y__h66 = { 4'b0, cf8143tofp_cf8143[6:3] } ;
  assign y__h67 = { 2'b0, cf8143tofp_bias } ;
endmodule  // mkCF8143toFP32

