//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Sun Dec 10 11:07:26 IST 2023
//
//
// Ports:
// Name                         I/O  size props
// fp32                           O    32
// RDY_fp32                       O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// fp32_bf16                      I    16
//
// Combinational paths from inputs to outputs:
//   fp32_bf16 -> fp32
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkBF16toFP32(CLK,
		    RST_N,

		    fp32_bf16,
		    fp32,
		    RDY_fp32);
  input  CLK;
  input  RST_N;

  // value method fp32
  input  [15 : 0] fp32_bf16;
  output [31 : 0] fp32;
  output RDY_fp32;

  // signals for module outputs
  wire [31 : 0] fp32;
  wire RDY_fp32;

  // value method fp32
  assign fp32 = { fp32_bf16, 16'b0 } ;
  assign RDY_fp32 = 1'd1 ;
endmodule  // mkBF16toFP32

